### ISSUE TITLE
KeyError in calculate_stats

### ISSUE THREAD

**Issue by psymar** [paoloruiz/ootp-pt-analysis#3]
Traceback (most recent call last):
  File "C:\Users\johnm\Dropbox\ootp-pt-analysis\generate_sheet.py", line 47, in <module>
    splits = get_splits(ovr_data_ylt, vl_data_ylt, vr_data_ylt, vl_data, vr_data)
  File "C:\Users\johnm\Dropbox\ootp-pt-analysis\stats\splits\calculate_splits.py", line 2, in get_splits
    catcher_full_time, catcher_vr, catcher_vl = _get_potential_catchers(ovr_data, vl_data_ylt, vr_data_ylt)
  File "C:\Users\johnm\Dropbox\ootp-pt-analysis\stats\splits\calculate_splits.py", line 64, in _get_potential_catchers
    if vl_data[year_league_team][pot_catchers[0]["CID"]]["gs"] > vl_data[year_league_team][pot_catchers[1]["cid"]]["gs"]:
KeyError: 'cid'

Fix is to change "cid" to "CID".  PR incoming.

**Comment by psymar** [comment]
https://github.com/paoloruiz/ootp-pt-analysis/pull/4

**Comment by paoloruiz** [comment]
#4 closed, will close this as well
